### ISSUE TITLE
error.FileNotFound

### ISSUE THREAD

**Issue by beyang** [zigtools/scip-zig#3]
I am new to Zig, so I imagine I'm doing something stupid here.

I installed zig and successfully built the scip-zig binary. My zig directory is at `$HOME/zig`.

I tried running `scip-zig --pkg std $HOME/zig/lib/std/std.zig --root std` and got the following error:
```
info: Loading --root
error: FileNotFound
/home/beyang/zig/lib/std/os.zig:1741:23: 0x239678 in std.os.openatZ (scip-zig)
            .NOENT => return error.FileNotFound,
                      ^
/home/beyang/zig/lib/std/fs.zig:1175:13: 0x21bf73 in std.fs.Dir.openFileZ (scip-zig)
            try os.openatZ(self.fd, sub_path, os_flags, 0);
            ^
/home/beyang/zig/lib/std/fs.zig:1102:9: 0x2191d1 in std.fs.Dir.openFile (scip-zig)
        return self.openFileZ(&path_c, flags);
        ^
/home/beyang/zig/lib/std/fs.zig:2718:5: 0x2446f5 in std.fs.openFileAbsolute (scip-zig)
    return cwd().openFile(absolute_path, flags);
    ^
/home/beyang/src/github.com/zigtools/scip-zig/src/analysis/DocumentStore.zig:77:16: 0x243db3 in analysis.DocumentStore.loadFile (scip-zig)
    var file = try std.fs.openFileAbsolute(concat_path, .{});
               ^
/home/beyang/src/github.com/zigtools/scip-zig/src/analysis/DocumentStore.zig:64:9: 0x242869 in analysis.DocumentStore.createPackage (scip-zig)
    _ = try store.loadFile(package, try std.fs.path.relative(store.allocator, store.root_path, root));
        ^
/home/beyang/src/github.com/zigtools/scip-zig/src/main.zig:49:17: 0x23f2e1 in main (scip-zig)
                try doc_store.createPackage(package_name.?, arg);
                ^
```

I also tried running `scip-zig --pkg std src/scip.zig --root scip-zig` and got the same error. Is there something obvious I'm missing? I'm not sure which file it's looking for. Haven't used Zig much before, just trying to generate an index and then upload to sourcegraph.com, because I think that would be pretty cool!

**Comment by SuperAuguste** [comment]
Oopsies, I changed how the command works recently and forgot to update the README!

`--root` is now `--root-pkg`! Also, you might want to specify `--root-path` as being `$HOME/zig` so the index root is correct - make sure to place the `--root-path` at the start of your invocation though, else it won't propagate properly. :)
