### ISSUE TITLE
broken in the master of zig

### ISSUE THREAD

**Issue by weejulius** [zigtools/scip-zig#5]
The project cannot compile using the master of zig, I try to fix the compile errors, but unfortunetely it failed to run. the detail is below. it seems it is caused by the change of for range syntax .

info: Loading lib/zig/std/std.zig
info(analyzer): Initializing file lib/zig/std/std.zig
info: Loading lib/zig/std/array_list.zig
info(analyzer): Initializing file lib/zig/std/array_list.zig
thread 2434576 panic: index out of bounds: index 11649, len 11648
/Users/jyu/code/scip-zig/src/analysis/utils.zig:193:23: 0x1042326bd in fullWhile (scip-zig)
        if (token_tags[result.else_token + 1] == .pipe) {

**Comment by SuperAuguste** [comment]
Hey @weejulius, thanks for your interest in scip-zig! Unfortunately, I haven't had the time to maintain this for quite a while. I plan on integrating this with zls as a library in the future but that'll take a bit. Sorry for the bad news. :(
